from tkinter import *
root=Tk()
root.geometry("350x200")
fr1=Frame(root)
fr1.pack(side='top')
btn1=Button(fr1, text='Button 1', width=10, height=5, bg='white',fg='black')
btn1.pack(side='left')
btn2=Button(fr1, text='Button 2', width=10, height=5, bg='white',fg='black')
btn2.pack(side='right', padx=5)
root.mainloop()
